### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by IsraelOrtuno** [webpatser/laravel-uuid#10]
Not really understand how this works at all but I need to generate a unique string from a real MAC address

```php
Uuid::generate(5, 'AABBCCDDEEFF', Uuid::NS_DNS);
```

But I need the result to be always the same for the same MAC address whenever I perform this task (now or future). Do you think this fits my needs?

**Comment by vjandrea** [comment]
@IsreaelOrtuno, looks like that you need more a hash than a random uuid.
MD5 is not the best in terms of security but outputs a 32 char string that you may format as an UUID; for more safety you may use a salt (i.e. md5($mac_address . $salt_string) or just truncate another hash at 32 char if you want strictly that length

**Comment by vjandrea** [comment]
@IsreaelOrtuno, looks like that you need more a hash than a random uuid.
MD5 is not the best in terms of security but outputs a 32 char string that you may format as an UUID; for more safety you may use a salt (i.e. md5($mac_address . $salt_string) or just truncate another hash at 32 char if you want strictly that length

**Comment by vjandrea** [comment]
@IsreaelOrtuno, looks like that you need more a hash than a random uuid.
MD5 is not the best in terms of security but outputs a 32 char string that you may format as an UUID; for more safety you may use a salt (i.e. md5($mac_address . $salt_string) or just truncate another hash at 32 char if you want strictly that length

**Comment by vjandrea** [comment]
@IsreaelOrtuno, looks like that you need more a hash than a random uuid.
MD5 is not the best in terms of security but outputs a 32 char string that you may format as an UUID; for more safety you may use a salt (i.e. md5($mac_address . $salt_string) or just truncate another hash at 32 char if you want strictly that length
