### ISSUE TITLE
Error in laravel 5.3, when i install the package with composer

### ISSUE THREAD

**Issue by ivelaval** [webpatser/laravel-uuid#19]
Error fixed. should not add the package in the providers.

**Comment by ivelaval** [comment]
Error

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing webpatser/laravel-uuid (2.0.1)
    Loading from cache

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to protected Webpatser\Uuid\Uuid::__construct() from context 'Illuminate\Foundation\ProviderRepository'


Script php artisan optimize handling the post-update-cmd event returned with error code 255

Installation failed, reverting ./composer.json to its original content.

**Comment by heisian** [comment]
Plz close issues if resolved! Thanks :]
