### ISSUE TITLE
[Question] Could it be possible to split the Uuid class to another repository

### ISSUE THREAD

**Issue by phoenixgao** [webpatser/laravel-uuid#22]
Could it be possible to split the Uuid class to another repository as a dependency, so that I could use that package in a non-laravel project?

Thanks

**Comment by KuroThing** [comment]
There isn't really anything Laravel related except for the Facade, [I mean the library doesn't even depend on laravel](https://github.com/webpatser/laravel-uuid/blob/master/composer.json#L16-L18)
