### ISSUE TITLE
Generate uuid with only 8 digits?

### ISSUE THREAD

**Issue by erdely** [webpatser/laravel-uuid#23]
Is there any possibility to create a uuid but only with 8 digits, as datatype integer?

**Comment by webpatser** [comment]
eeh no. UUID is 128-bit value so creating an 8-bit version is kinda hard. If you need an 8-bit random integer. Just use the rand() option. But I guess this would give collisions fast :-)

**Comment by erdely** [comment]
I know how to create random, but not unique ;)

Anyway this plugin is very, very good, thank you!

**Comment by webpatser** [comment]
depending why you need a random integer. If you only need it to obscure an URL (not wanting to display the ID), you can also add the UUID in a separate char(36) field. And use that in your URL's.

**Comment by erdely** [comment]
I need that as "customer number", this id will be printed on cards, of course must be unique. For url's I have used your solution

**Comment by danielsdeboer** [comment]
You could alter your auto incrementing id column to start at 10000000 or something like that and just use the id as the customer number.

**Comment by tanveerahmaddar** [comment]
you can do it this way

// With this precision (microsecond) ID will looks like '2di2adajgq6h'
$id = base_convert(microtime(false), 10, 36);

// With less precision (second) ID will looks like 'niu7pj'
$id = base_convert(time(), 10, 36);
