### ISSUE TITLE
Laravel findOrFail support

### ISSUE THREAD

**Issue by sandervanhooft** [webpatser/laravel-uuid#24]
Hi,

While using the `findOrFail(id)` method, I noticed that Eloquent returns a record matching a different `id` than the one I pass in. It does not throw an error, so it took me some time to find this flaw.

Am I correct to assume that `findOrFail()` is currently not supported by this package?

Kind regards,

Sander

**Comment by ctf0** [comment]
maybe because the default model PK type is 
```php
    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'int';
```

and it should be changed to `varchar` http://mysqlserverteam.com/storing-uuid-values-in-mysql-tables/ ?

unfortunately the packaged docs isn't sufficient regarding using it for table PK.

**Comment by sandervanhooft** [comment]
Hi @ctf0 ,

See [here](https://github.com/alsofronie/eloquent-uuid/commit/3676c1fafbc063c9f5f206a702b23c5c6999e072), this repo has fixed the problem with a `findOrFail` trait.

**Comment by monaam** [comment]
@sandervanhooft that repo was actually to work with a binary type column, not relevant i'm afraid

**Comment by webpatser** [comment]
I updated the readme with an Eloquent section. Maybe this is what you need.
