### ISSUE TITLE
Missing license file?

### ISSUE THREAD

**Issue by mllapps** [webpatser/laravel-uuid#28]
Hello, I want to use your library at personal project. But I need a MIT or BSD licensed library. I can not find a license file here. Please add one.

**Comment by SylvesterNielsen** [comment]
Same here. Please include a license so we know in which extend we are allowed to use the code.

**Comment by webpatser** [comment]
As you can see in the composer.json

``
"license" : [
	"MIT"
],
``

I will make it a bit more clear in the readme with the next update

**Comment by webpatser** [comment]
The readme is updated and now show the correct licence badge grabbed from composer.json :-)
