### ISSUE TITLE
Laravel 5 broken

### ISSUE THREAD

**Issue by renege** [webpatser/laravel-uuid#3]
```<h1>Whoops, looks like something went wrong.</h1>
                                        <h2 class="block_exception clear_fix">
                            <span class="exception_counter">1/1</span>
                            <span class="exception_title"><abbr title="Symfony\Component\Debug\Exception\FatalErrorException">FatalErrorException</abbr> in <a title="/home/vagrant/Code/xxxxx/app/Http/Controllers/PhotosController.php line 40" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">PhotosController.php line 40</a>:</span>
                            <span class="exception_message">Class &#039;App\Http\Controllers\Uuid&#039; not found</span>````

added it to aliasses...

**Comment by webpatser** [comment]
I'll check why the Facade is not working. Adding the correct namespace to the controller should work too..

**Comment by webpatser** [comment]
Also from the larval 5 docs:

Importing Facades

Remember, if you are using a facade in a controller that is namespaced, you will need to import the facade class into the namespace. All facades live in the global namespace:

<?php namespace App\Http\Controllers;

use Cache;

class PhotosController extends Controller {

    /**
     * Get all of the application photos.
     *
     * @return Response
     */
    public function index()
    {
        $photos = Cache::get('photos');

        //
    }

}

**Comment by webpatser** [comment]
To clarify:

when the alias is in the config you can use the namespace
    use Uuid;

if the alias is missing you can reference the complete path
    use Webpatser\Uuid\Uuid
