### ISSUE TITLE
Call to undefined method Webpatser\Uuid\UuidFacade::generate() in Laravel 5.5

### ISSUE THREAD

**Issue by dees040** [webpatser/laravel-uuid#34]
When upgrading Laravel from 5.4 to 5.5 I got the following error:

`Call to undefined method Webpatser\\Uuid\\UuidFacade::generate()`

I'm using `'Uuid' => Webpatser\Uuid\Uuid::class,` in my aliases.

My code:

```php
static::creating(function ($model) {
     $model->{$model->getKeyName()} = Uuid::generate()->string;
});
```

**Comment by wmlab03** [comment]
Same issue, Did you get any solution for this?

**Comment by sebas-nicholls** [comment]
I have the same issue

**Comment by webpatser** [comment]
I will look into it :-)

**Comment by webpatser** [comment]
Done. Fixed in version 2.1.

```json
"webpatser/laravel-uuid": "^2.0"
```

**Comment by webpatser** [comment]
small update: Version 3.0 is laravel 5.5 ready, and php 7 only!

**Comment by lakshmaji** [comment]
`Uuid is not found` error when trying to generate uuid from the controller 
`Uuid::generate(4);`

#### Environment details
- Laravel 5.4
- PHP 7.1

**Comment by webpatser** [comment]
Did you import the class?

**Comment by lakshmaji** [comment]
Yes, and it was like below
`php use Uuid;`
