### ISSUE TITLE
Doesn't work without facades [Lumen]

### ISSUE THREAD

**Issue by 4levels** [webpatser/laravel-uuid#40]
Hi,

I'm trying to use your great library in a Lumen project without using Facades (imho Facades are userland tools).
I'd also love to see some info on how to implement this in Lumen.

I've managed so far by creating a custom UuidServiceProvider that includes a register() function, and I replaced all facade calls.  I'll make a PR later on so you can review my changes..

Thanks for this already!

Kind regards

**Comment by webpatser** [comment]
You can also just import the Uuid class and use it directly where needed?
