### ISSUE TITLE
Uuid-3.0 is not working with laravel 5.5 

### ISSUE THREAD

**Issue by lakshmaji** [webpatser/laravel-uuid#43]
`Uuid is not found` error when trying to generate uuid from the controller 
`Uuid::generate(4);`

#### Environment details
- Laravel 5.4
- PHP 7.1
- Uuid 3.0

**Comment by BenExile** [comment]
Multiple contradications in your issue report:

- Title states Laravel 5.5, description states 5.4
- Title states UUID version 3, example uses UUID version 4

Can you clarify?

**Comment by webpatser** [comment]
Latest version works in both laravel 5.4 and 5.5.

Like @BenExile, can you explain a bit more what you are trying to do?

**Comment by lakshmaji** [comment]
Yeah that was a typo, Thanks @BenExile  and the **Laravel** version I'm using was **5.5**

- Currently I'm using 'Webpatser\Uuid\ Uuid::generate(4)` , No issues with this.
- But why can't I simply use with help of facades in my controller class, like as illustrated below

`Uuid:: generate(4) `

**Comment by BenExile** [comment]
You don't need to use a facade to do this. Just import the `Uuid` class as you would with any other class:

```php
use Webpatser\Uuid\Uuid;
$uuid = Uuid::generate(4);
```

**Comment by lakshmaji** [comment]
Yeah it worked for me

**Comment by hightekjonathan** [comment]
If you really want to use a Facade for blade directives/whatever, you can paste this line in the Facades array at the end of your `config/app.php`

`'Uuid' => Webpatser\Uuid\Uuid::class,`

And then you should be able to use it as so

`Uuid::generate();`

**Comment by lakshmaji** [comment]
@hightekjonathan , Yeah that's right. but this package has enabled package `auto discovery`. So it it is not required to register  `facades` manually. Am I missing anything here
