### ISSUE TITLE
FatalThrowableError 

### ISSUE THREAD

**Issue by saifuldhaka** [webpatser/laravel-uuid#53]
I am using laravel 5.4 and version 2
it working in my localhost but when i upload in my staging server, it showing error

![jghjghjghj](https://user-images.githubusercontent.com/2381203/42146747-5eb88590-7dfc-11e8-9b77-8a875b3febcb.png)

**Comment by webpatser** [comment]
Is your webserver on a different PHP version?

**Comment by saifuldhaka** [comment]
php version ea-php71

**Comment by saifuldhaka** [comment]
webserver PHP version : 7.1

**Comment by webpatser** [comment]
It fails to load the facade, is your app.php config the same?

**Comment by saifuldhaka** [comment]
https://dev.shopavision.com/
please check the error here


(1/1) FatalThrowableErrorCall to protected Webpatser\Uuid\Uuid::__construct() from context 'Illuminate\Foundation\ProviderRepository'
--
in ProviderRepository.php line 208

**Comment by BonnieSawe** [comment]
any luck on this?
