### ISSUE TITLE
Lumen 6.3.2 - did not autodiscover - Class 'Uuid' not found

### ISSUE THREAD

**Issue by dodancs** [webpatser/laravel-uuid#63]
Hey, I wanted to use this for my API, and after running composer require, I tried to use the library in my code, but was unsuccessfull.

It seems like Lumen does not know anything about it.

Help please?

**Comment by ext-rgonzalez** [comment]
hi 

You can use the webpaster uuid class

use Webpatser\Uuid\Uuid;

**Comment by ext-rgonzalez** [comment]
> Hey, I wanted to use this for my API, and after running composer require, I tried to use the library in my code, but was unsuccessfull.
> 
> It seems like Lumen does not know anything about it.
> 
> Help please?

hi

You can use the webpaster uuid class

use Webpatser\Uuid\Uuid;

**Comment by ssi-anik** [comment]
- Lumen doesn't support auto-discovery.
- You'll only need the service provider if you want to validate your request. Otherwise, the service provider isn't mandatory.

**Comment by rjdjohnston** [comment]
This should be in the README file.

`use Webpatser\Uuid\Uuid;`
