### ISSUE TITLE
Switch to FakerPHP/Faker

### ISSUE THREAD

**Issue by bramceulemans** [webpatser/laravel-uuid#67]
Since <https://packagist.org/packages/fzaninotto/faker> is now abandoned.

Link to FakerPHP/Faker: <https://github.com/FakerPHP/Faker>.

**Comment by Milanowicz** [comment]
Should be fixed, my PR has been merged and I have had it myself that this is outdated.

PR: https://github.com/webpatser/laravel-uuid/pull/68

**Comment by webpatser** [comment]
Too ensure backwards compatibility. The latest merges for PHP8 are now tagged as version 4.0

**Comment by Milanowicz** [comment]
Nice and good to know @webpatser :+1:
