### ISSUE TITLE
Doesn't generate uuid on relation table?

### ISSUE THREAD

**Issue by guodong** [webpatser/laravel-uuid#8]

**Comment by webpatser** [comment]
eeh.. What do you mean exactly?

**Comment by guodong** [comment]
In case I have model and table user, role, role_user, in the following code:
```
$user->role()->attach($role->id); 
```
It will not generate uuid in role_user.id

**Comment by webpatser** [comment]
IF you want to automatically get uuid generated in your model you need to hook into the model events

for example: put this into your model soit adds an uuid when a new record as about to be persisted.

```php
/**
     *  Setup model event hooks
     */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($table) {
            // Generate uuid
            $table->uuid = Uuid::generate(4);
        });
    }
```

also check: http://laravel.com/docs/5.1/eloquent#events

**Comment by guodong** [comment]
sorry, maybe I didn't descript it clearly. My problem is Model tables can generate uuid automatically, but relation table liek role_user doesn't has a model, so primary key in relation table will not be set a uuid but an empty value(trigger database auto inc on primary).

**Comment by webpatser** [comment]
Maybe you can find more info on storing data in the pivot tables here :-)

http://laravel.com/docs/4.2/eloquent#working-with-pivot-tables

**Comment by shaneparsons** [comment]
@webpatser You should include those instructions, a few comments up, somewhere in the readme. They're quite helpful.
